version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.11.2-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - desktop-cache-{{ checksum "package.json" }}
          - cache-yarn

      - run:
          name: Pre Checks
          command: |
            if git status --short | grep yarn\.lock; then echo 'yarn.lock is not updated'; false; else true; fi
            npm run build
            npm run package:windows
            npm run package:mac
            npm run package:linux
            sh -x ./scripts/cp_artifacts.sh release $CIRCLE_ARTIFACTS

      - save_cache:
          paths:
            - "src/node_modules"
          key: desktop-dependencies-{{ checksum "package.json" }}
            - ~/.cache/yarn
          key: cache-yarn-{{ checksum "package.json" }}

      - run: yarn test

      - store_artifacts:
          path: test-results.xml
          prefix: tests


