version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.3

    working_directory: ~/desktop

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - desktop-cache-{{ checksum "package.json" }}
          - cache-yarn
      - run:
          name: yarn install
          command: 'yarn'
      - run:
          name: Pre Checks
          command: |
            if git status --short | grep yarn\.lock; then echo 'yarn.lock is not updated'; false; else true; fi
      - run:
          name: npm run build
          command: 'npm run build'

      - run:
          name: Package Windows
          command: 'npm run package:windows'

      - run:
          name: Package Mac
          command: 'npm run package:mac'

      - run:
          name: Package Linux
          command: 'npm run package:linux'

      - save_cache:
          paths:
            - "src/node_modules"
          key: desktop-dependencies-{{ checksum "package.json" }}
            - ~/.cache/yarn
          key: cache-yarn-{{ checksum "package.json" }}

      - run: yarn test

      - store_artifacts:
          path: test-results.xml
          prefix: tests


